title: Twilight of something
author: Me the Majestique
email: pure-bone@king.dom
description: > # this means to ignore newlines until "baseurl:"
  So sha-la-la
    la-la-la
      la-la

# social links
twitter_username: pure-bone # DO NOT include the @ character, or else the build will fail!
github_username:  pure-bon # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
